---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2019
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: "controller01"
  memory: 8192
  cpus: 2
  role: "controlPlane"
- name: "controller02"
  memory: 8192
  cpus: 2
  role: "controlPlane"
- name: "controller03"
  memory: 8192
  cpus: 2
  role: "controlPlane"
- name: "compute01"
  memory: 32768
  cpus: 16
  role: "compute"
- name: "compute02"
  memory: 8192
  cpus: 4
  role: "compute"
